#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
This parser processes the aggregated `interfaces_all.csv` (generated by interface2connection.py or interface_status.py)
to extract Business Service and Client Inventory data based on structured Interface Descriptions.

Expected target patterns (examples):
CLIENTE_INSS_VIA_P-CORD_CPE-CLI*INTER-BK*ACSDB00002*20MBPS*RTCE-RBO016-02
PEERING_PTT-PA_IPV4*PAPT000001*10GBPS*2022/09/19
TRANSITO_TELEFONICA*F-OPTICA*STIC-0000401745*10GBPS*2022/09/19

Fields are separated by '*'
"""

import os
import csv
import argparse

def extract_service_inventory(resume_dir):
    interfaces_file = os.path.join(resume_dir, "interfaces_all.csv")
    out_file = os.path.join(resume_dir, "service_inventory_all.csv")
    
    if not os.path.isfile(interfaces_file):
        print(f" -> File not found: {interfaces_file}")
        return

    csv.field_size_limit(10000000)
    services = []

    with open(interfaces_file, 'r', encoding='utf-8', errors='ignore') as f:
        reader = csv.DictReader(f, delimiter=';')
        
        for row in reader:
            desc = row.get('description', '').strip()
            
            # We are only interested in descriptions that identify external business relationships
            if desc.startswith('CLIENTE_') or desc.startswith('PEERING_') or desc.startswith('TRANSITO_'):
                # Extract the entity type and the rest of the string
                parts = desc.split('*')
                
                # Basic normalization
                entity_info = parts[0]
                entity_type = entity_info.split('_')[0] if '_' in entity_info else entity_info
                client_name = entity_info.replace('CLIENTE_', '').replace('PEERING_', '').replace('TRANSITO_', '')
                
                # Safe extraction of elements knowing it normally follows: Name * Type * ID * Speed * Date/Destination
                conn_type = parts[1] if len(parts) > 1 else ""
                contract_id = parts[2] if len(parts) > 2 else ""
                speed = parts[3] if len(parts) > 3 else ""
                
                # Suffix data might be a date or a CPE name. Let's just capture the rest loosely
                extra_data = "*".join(parts[4:]) if len(parts) > 4 else ""

                services.append({
                    'Element': row.get('element', ''),
                    'Interface': row.get('interface', ''),
                    'Entity_Type': entity_type,
                    'Entity_Name': client_name,
                    'Connection_Type': conn_type,
                    'Contract_ID': contract_id,
                    'Speed': speed,
                    'Extra_Identifier': extra_data,
                    'Admin_Status': row.get('admin_status', ''),
                    'Line_Protocol': row.get('line_protocol', ''),
                    'Raw_Description': desc
                })

    # Write Output
    with open(out_file, 'w', newline='', encoding='utf-8') as csvfile:
        fieldnames = [
            'Element', 'Interface', 'Entity_Type', 'Entity_Name', 'Connection_Type', 
            'Contract_ID', 'Speed', 'Extra_Identifier', 'Admin_Status', 'Line_Protocol', 'Raw_Description'
        ]
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames, delimiter=';')
        writer.writeheader()
        
        for srv in services:
            writer.writerow(srv)
            
    print(f" -> Generated: {out_file} ({len(services)} services cataloged)")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Extract Service Inventory from interfaces aggregate")
    parser.add_argument("--resume_dir", required=True, help="Path to the resume directory containing interfaces_all.csv")
    args = parser.parse_args()
    
    extract_service_inventory(args.resume_dir)
